2022-01-30 22:47:59,904 - Database Import - INFO - Sever Connected !
2022-01-30 22:47:59,993 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-30 22:48:00,021 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-30 22:48:00,136 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-30 22:48:00,167 - Database Import - INFO - CPI Yearly.csv file created
2022-01-30 22:48:00,196 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-30 22:48:00,306 - Database Import - INFO - CPI Monthly.csv file created
2022-01-30 22:49:18,193 - Database Import - INFO - Sever Connected !
2022-01-30 22:49:18,292 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-30 22:49:18,324 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-30 22:49:18,478 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-30 22:49:18,520 - Database Import - INFO - CPI Yearly.csv file created
2022-01-30 22:49:18,550 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-30 22:49:18,640 - Database Import - INFO - CPI Monthly.csv file created
2022-01-30 22:56:55,280 - Database Import - INFO - Sever Connected !
2022-01-30 22:56:55,323 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-30 22:56:55,337 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-30 22:56:55,453 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-30 22:56:55,490 - Database Import - INFO - CPI Yearly.csv file created
2022-01-30 22:56:55,515 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-30 22:56:55,605 - Database Import - INFO - CPI Monthly.csv file created
2022-01-30 22:57:00,178 - Database Import - INFO - Sever Connected !
2022-01-30 22:57:00,245 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-30 22:57:00,261 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-30 22:57:00,376 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-30 22:57:00,403 - Database Import - INFO - CPI Yearly.csv file created
2022-01-30 22:57:00,427 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-30 22:57:00,515 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:27:14,136 - Database Import - INFO - Sever Connected !
2022-01-31 22:27:14,201 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:27:14,217 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:27:14,348 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:27:14,382 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:27:14,413 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:27:14,518 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:27:18,752 - Database Import - INFO - Sever Connected !
2022-01-31 22:27:18,816 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:27:18,827 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:27:18,924 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:27:18,952 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:27:18,989 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:27:19,109 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:27:26,777 - Database Import - INFO - Sever Connected !
2022-01-31 22:27:26,844 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:27:26,865 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:27:27,060 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:27:27,110 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:27:27,172 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:27:27,286 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:27:37,996 - Database Import - INFO - Sever Connected !
2022-01-31 22:27:38,031 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:27:38,047 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:27:38,158 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:27:38,196 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:27:38,223 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:27:38,318 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:27:48,263 - Database Import - INFO - Sever Connected !
2022-01-31 22:27:48,321 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:27:48,335 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:27:48,448 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:27:48,481 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:27:48,515 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:27:48,665 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:28:30,688 - Database Import - INFO - Sever Connected !
2022-01-31 22:28:30,724 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:28:30,738 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:28:30,834 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:28:30,867 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:28:30,898 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:28:31,024 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:29:14,800 - Database Import - INFO - Sever Connected !
2022-01-31 22:29:14,847 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:29:14,866 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:29:14,996 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:29:15,033 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:29:15,060 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:29:15,147 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:30:00,868 - Database Import - INFO - Sever Connected !
2022-01-31 22:30:00,938 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:30:00,965 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:30:01,066 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:30:01,095 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:30:01,122 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:30:01,213 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:30:14,411 - Database Import - INFO - Sever Connected !
2022-01-31 22:30:14,497 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:30:14,525 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:30:14,687 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:30:14,725 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:30:14,759 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:30:14,878 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:33:59,840 - Database Import - INFO - Sever Connected !
2022-01-31 22:33:59,878 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:33:59,898 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:33:59,992 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:34:00,029 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:34:00,058 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:34:00,166 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:34:48,642 - Database Import - INFO - Sever Connected !
2022-01-31 22:34:48,698 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:34:48,711 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:34:48,806 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:34:48,836 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:34:48,865 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:34:48,959 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:39:42,716 - Database Import - INFO - Sever Connected !
2022-01-31 22:39:42,784 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:39:42,799 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:39:42,887 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:39:42,918 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:39:42,944 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:39:43,028 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:40:55,908 - Database Import - INFO - Sever Connected !
2022-01-31 22:40:55,984 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:40:55,996 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:40:56,090 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:40:56,117 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:40:56,154 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:40:56,248 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:40:59,500 - Database Import - INFO - Sever Connected !
2022-01-31 22:40:59,554 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:40:59,570 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:40:59,666 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:40:59,696 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:40:59,723 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:40:59,811 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:41:32,238 - Database Import - INFO - Sever Connected !
2022-01-31 22:41:32,284 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:41:32,295 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:41:32,390 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:41:32,417 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:41:32,443 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:41:32,541 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:41:32,558 - Database Import - INFO - Sever Connected !
2022-01-31 22:41:32,558 - Database Import - INFO - Sever Connected !
2022-01-31 22:41:32,594 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:41:32,594 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:41:32,611 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:41:32,611 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:41:32,728 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:41:32,728 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:41:32,758 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:41:32,758 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:41:32,794 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:41:32,794 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:41:32,895 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:41:32,895 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:41:48,990 - Database Import - INFO - Sever Connected !
2022-01-31 22:41:49,041 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:41:49,053 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:41:49,161 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:41:49,192 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:41:49,219 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:41:49,324 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:41:49,340 - Database Import - INFO - Sever Connected !
2022-01-31 22:41:49,340 - Database Import - INFO - Sever Connected !
2022-01-31 22:41:49,380 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:41:49,380 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:41:49,396 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:41:49,396 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:41:49,526 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:41:49,526 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:41:49,560 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:41:49,560 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:41:49,592 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:41:49,592 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:41:49,708 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:41:49,708 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:42:06,596 - Database Import - INFO - Sever Connected !
2022-01-31 22:42:06,682 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:42:06,695 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:42:06,794 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:42:06,824 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:42:06,852 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:42:06,940 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:42:06,954 - Database Import - INFO - Sever Connected !
2022-01-31 22:42:06,954 - Database Import - INFO - Sever Connected !
2022-01-31 22:42:06,999 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:42:06,999 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:42:07,011 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:42:07,011 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:42:07,109 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:42:07,109 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:42:07,139 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:42:07,139 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:42:07,164 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:42:07,164 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:42:07,258 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:42:07,258 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:42:29,488 - Database Import - INFO - Sever Connected !
2022-01-31 22:42:29,554 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:42:29,566 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:42:29,663 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:42:29,690 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:42:29,714 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:42:29,807 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:42:29,822 - Database Import - INFO - Sever Connected !
2022-01-31 22:42:29,822 - Database Import - INFO - Sever Connected !
2022-01-31 22:42:29,855 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:42:29,855 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:42:29,868 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:42:29,868 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:42:29,975 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:42:29,975 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:42:30,008 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:42:30,008 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:42:30,036 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:42:30,036 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:42:30,159 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:42:30,159 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:43:02,132 - Database Import - INFO - Sever Connected !
2022-01-31 22:43:02,239 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:43:02,250 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:43:02,342 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:43:02,371 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:43:02,397 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:43:02,489 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:43:02,504 - Database Import - INFO - Sever Connected !
2022-01-31 22:43:02,504 - Database Import - INFO - Sever Connected !
2022-01-31 22:43:02,544 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:43:02,544 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:43:02,556 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:43:02,556 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:43:02,655 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:43:02,655 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:43:02,683 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:43:02,683 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:43:02,711 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:43:02,711 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:43:02,814 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:43:02,814 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:43:26,708 - Database Import - INFO - Sever Connected !
2022-01-31 22:43:26,774 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:43:26,786 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:43:26,886 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:43:26,915 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:43:26,942 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:43:27,027 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:43:27,042 - Database Import - INFO - Sever Connected !
2022-01-31 22:43:27,042 - Database Import - INFO - Sever Connected !
2022-01-31 22:43:27,073 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:43:27,073 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-01-31 22:43:27,089 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:43:27,089 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-01-31 22:43:27,185 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:43:27,185 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-01-31 22:43:27,218 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:43:27,218 - Database Import - INFO - CPI Yearly.csv file created
2022-01-31 22:43:27,258 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:43:27,258 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-01-31 22:43:27,361 - Database Import - INFO - CPI Monthly.csv file created
2022-01-31 22:43:27,361 - Database Import - INFO - CPI Monthly.csv file created
2022-02-01 18:04:18,556 - Database Import - INFO - Sever Connected !
2022-02-01 18:04:48,800 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f928ca7c11e63fa1a648dc, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f928ca7c11e63fa1a648dc, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:04:51,040 - Database Import - INFO - Sever Connected !
2022-02-01 18:05:21,213 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f928eb3a74739028e8f7b6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f928eb3a74739028e8f7b6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:08:13,234 - Database Import - INFO - Sever Connected !
2022-02-01 18:08:13,333 - Database Import - INFO - Sever Connected !
2022-02-01 18:08:43,474 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929b5e483775d580f3eb7, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929b5e483775d580f3eb7, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:08:43,474 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929b50cce637fa3eaaff5, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929b50cce637fa3eaaff5, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:08:43,504 - Database Import - INFO - Sever Connected !
2022-02-01 18:08:43,504 - Database Import - INFO - Sever Connected !
2022-02-01 18:09:13,737 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929d30cce637fa3eaaff6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929d30cce637fa3eaaff6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:09:13,737 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929d30cce637fa3eaaff6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f929d30cce637fa3eaaff6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:25:07,632 - Database Import - INFO - Sever Connected !
2022-02-01 18:25:37,830 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f92dab4a586021777c26d2, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f92dab4a586021777c26d2, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:26:17,720 - Database Import - INFO - Sever Connected !
2022-02-01 18:26:47,820 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f92df1246845bacbadf82a, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f92df1246845bacbadf82a, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:37:47,635 - Database Import - INFO - Sever Connected !
2022-02-01 18:37:54,033 - Database Import - INFO - Sever Connected !
2022-02-01 18:38:17,896 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930a31c1fb878804ba7c1, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930a31c1fb878804ba7c1, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:38:24,253 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930aa57447c3328dfd92e, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930aa57447c3328dfd92e, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:38:24,272 - Database Import - INFO - Sever Connected !
2022-02-01 18:38:24,272 - Database Import - INFO - Sever Connected !
2022-02-01 18:38:32,509 - Database Import - INFO - Sever Connected !
2022-02-01 18:38:35,508 - Database Import - INFO - Sever Connected !
2022-02-01 18:39:02,758 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930d0a39a7c2d778875d6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930d0a39a7c2d778875d6, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:39:05,734 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930d3f0195af8ec3845ea, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f930d3f0195af8ec3845ea, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:39:57,802 - Database Import - INFO - Sever Connected !
2022-02-01 18:39:59,548 - Database Import - INFO - Sever Connected !
2022-02-01 18:40:28,009 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93125ed8533bd175eff23, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93125ed8533bd175eff23, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:40:29,813 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93127540d215f0544743f, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93127540d215f0544743f, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:44:15,368 - Database Import - INFO - Sever Connected !
2022-02-01 18:44:46,736 - Database Import - INFO - Sever Connected !
2022-02-01 18:45:17,003 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f932460b7404f1506103f0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f932460b7404f1506103f0, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:45:18,772 - Database Import - INFO - Sever Connected !
2022-02-01 18:45:48,986 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93266e243df887c22c8a8, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93266e243df887c22c8a8, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:57:52,164 - Database Import - INFO - Sever Connected !
2022-02-01 18:58:22,472 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93558c87652bdba777269, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f93558c87652bdba777269, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-01 18:58:23,569 - Database Import - INFO - Sever Connected !
2022-02-01 18:58:54,040 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f935779ce6d92c6e36c476, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61f935779ce6d92c6e36c476, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-02 01:00:07,247 - Database Import - INFO - Sever Connected !
2022-02-02 01:00:07,296 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:00:08,713 - Database Import - INFO - Sever Connected !
2022-02-02 01:00:08,729 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:04:47,134 - Database Import - INFO - Sever Connected !
2022-02-02 01:04:47,150 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:08:22,351 - Database Import - INFO - Sever Connected !
2022-02-02 01:08:22,375 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:08:30,577 - Database Import - INFO - Sever Connected !
2022-02-02 01:08:30,594 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:22:40,867 - Database Import - INFO - Sever Connected !
2022-02-02 01:22:40,898 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:24:01,227 - Database Import - INFO - Sever Connected !
2022-02-02 01:24:01,248 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:25:04,686 - Database Import - INFO - Sever Connected !
2022-02-02 01:25:04,700 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:25:19,689 - Database Import - INFO - Sever Connected !
2022-02-02 01:25:19,705 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:26:45,228 - Database Import - INFO - Sever Connected !
2022-02-02 01:26:45,243 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:27:57,462 - Database Import - INFO - Sever Connected !
2022-02-02 01:27:57,494 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:28:46,865 - Database Import - INFO - Sever Connected !
2022-02-02 01:28:46,880 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:29:49,356 - Database Import - INFO - Sever Connected !
2022-02-02 01:29:49,393 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:29:59,147 - Database Import - INFO - Sever Connected !
2022-02-02 01:29:59,162 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:30:26,275 - Database Import - INFO - Sever Connected !
2022-02-02 01:30:26,292 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 01:30:27,277 - Database Import - INFO - Sever Connected !
2022-02-02 01:30:27,295 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-02 14:47:18,671 - Database Import - INFO - Sever Connected !
2022-02-02 14:47:19,221 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 19:06:13,879 - Database Import - INFO - Sever Connected !
2022-02-03 19:06:14,620 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 20:51:09,566 - Database Import - INFO - Sever Connected !
2022-02-03 20:51:09,636 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 20:52:24,925 - Database Import - INFO - Sever Connected !
2022-02-03 20:52:24,940 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 20:53:34,573 - Database Import - INFO - Sever Connected !
2022-02-03 20:53:34,607 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 20:54:42,224 - Database Import - INFO - Sever Connected !
2022-02-03 20:54:42,250 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 20:57:12,581 - Database Import - INFO - Sever Connected !
2022-02-03 20:57:12,625 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 20:58:02,621 - Database Import - INFO - Sever Connected !
2022-02-03 20:58:02,670 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:00:59,238 - Database Import - INFO - Sever Connected !
2022-02-03 21:00:59,271 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:01:28,557 - Database Import - INFO - Sever Connected !
2022-02-03 21:01:28,609 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:02:53,665 - Database Import - INFO - Sever Connected !
2022-02-03 21:02:53,692 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:09:07,634 - Database Import - INFO - Sever Connected !
2022-02-03 21:09:07,659 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:10:12,432 - Database Import - INFO - Sever Connected !
2022-02-03 21:10:12,468 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:10:45,429 - Database Import - INFO - Sever Connected !
2022-02-03 21:10:45,455 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:12:49,716 - Database Import - INFO - Sever Connected !
2022-02-03 21:12:49,751 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:13:21,314 - Database Import - INFO - Sever Connected !
2022-02-03 21:13:21,360 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:13:42,291 - Database Import - INFO - Sever Connected !
2022-02-03 21:13:42,346 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-03 21:13:55,419 - Database Import - INFO - Sever Connected !
2022-02-03 21:13:55,436 - Database Import - ERROR - "['_id'] not found in axis"
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 129, in import_to_csv
    df.drop(["_id"], axis=1, inplace=True)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\frame.py", line 4906, in drop
    return super().drop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4150, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\generic.py", line 4185, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pandas\core\indexes\base.py", line 6017, in drop
    raise KeyError(f"{labels[mask]} not found in axis")
KeyError: "['_id'] not found in axis"
2022-02-04 19:01:08,858 - Database Import - INFO - Sever Connected !
2022-02-04 19:01:39,017 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd2a9c4517d1b921a4eb20, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd2a9c4517d1b921a4eb20, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-04 19:05:39,100 - Database Import - INFO - Sever Connected !
2022-02-04 19:06:09,335 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd2bab9cc8cc71a8f54b21, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd2bab9cc8cc71a8f54b21, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-04 19:07:19,144 - Database Import - INFO - Sever Connected !
2022-02-04 19:07:49,341 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd2c0fad416aedabe53ba1, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd2c0fad416aedabe53ba1, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-04 22:30:17,730 - Database Import - INFO - Sever Connected !
2022-02-04 22:30:47,746 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd5ba1ce4ead8442cb7e0e, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(01-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 61fd5ba1ce4ead8442cb7e0e, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 20:43:28,652 - Database Import - INFO - Sever Connected !
2022-02-07 20:43:58,998 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013718797284af2a19ed68, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013718797284af2a19ed68, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 20:44:01,030 - Database Import - INFO - Sever Connected !
2022-02-07 20:44:31,218 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 620137398455106af0021459, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 620137398455106af0021459, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 20:52:58,120 - Database Import - INFO - Sever Connected !
2022-02-07 20:53:28,330 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 620139524c6b5a207769eeb2, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 620139524c6b5a207769eeb2, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 20:53:30,147 - Database Import - INFO - Sever Connected !
2022-02-07 20:54:00,318 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013972f181af0764a2846f, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013972f181af0764a2846f, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 21:12:38,695 - Database Import - INFO - Sever Connected !
2022-02-07 21:13:08,833 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013dee6d70d854d12c545b, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013dee6d70d854d12c545b, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 21:13:10,961 - Database Import - INFO - Sever Connected !
2022-02-07 21:13:41,099 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013e0eda6fb24f23ac929a, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013e0eda6fb24f23ac929a, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 21:18:03,546 - Database Import - INFO - Sever Connected !
2022-02-07 21:18:07,652 - Database Import - INFO - Sever Connected !
2022-02-07 21:18:37,825 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013f37de4aca5591296a69, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013f37de4aca5591296a69, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-07 21:18:39,809 - Database Import - INFO - Sever Connected !
2022-02-07 21:19:09,970 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013f57b41c8492766965f8, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62013f57b41c8492766965f8, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-08 19:58:09,302 - Database Import - INFO - Sever Connected !
2022-02-08 19:58:39,664 - Database Import - ERROR - localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62027df9d848944b839e7976, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
Traceback (most recent call last):
  File "E:\Drive E\Bussiness analytics project\WebApp\Webappv2\flask_app(05-02-2022)\load_data\database_import.py", line 127, in import_to_csv
    loaded_data = list(cursor)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1159, in next
    if len(self.__data) or self._refresh():
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\cursor.py", line 1057, in _refresh
    self.__session = self.__collection.database.client._ensure_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1603, in _ensure_session
    return self.__start_session(True, causal_consistency=False)
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1553, in __start_session
    server_session = self._get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\mongo_client.py", line 1589, in _get_server_session
    return self._topology.get_server_session()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 530, in get_server_session
    session_timeout = self._check_session_support()
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 514, in _check_session_support
    self._select_servers_loop(
  File "C:\Users\Abhishek\Anaconda3\envs\WebApp\lib\site-packages\pymongo\topology.py", line 216, in _select_servers_loop
    raise ServerSelectionTimeoutError(
pymongo.errors.ServerSelectionTimeoutError: localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it, Timeout: 30s, Topology Description: <TopologyDescription id: 62027df9d848944b839e7976, topology_type: Unknown, servers: [<ServerDescription ('localhost', 27017) server_type: Unknown, rtt: None, error=AutoReconnect('localhost:27017: [WinError 10061] No connection could be made because the target machine actively refused it')>]>
2022-02-12 14:58:15,983 - Database Import - INFO - Sever Connected !
2022-02-12 14:58:16,019 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 14:58:16,030 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 14:58:16,117 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 14:58:16,144 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 14:58:16,168 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 14:58:16,245 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 14:59:21,163 - Database Import - INFO - Sever Connected !
2022-02-12 14:59:21,211 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 14:59:21,234 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 14:59:21,332 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 14:59:21,362 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 14:59:21,387 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 14:59:21,468 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 14:59:27,846 - Database Import - INFO - Sever Connected !
2022-02-12 14:59:27,880 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 14:59:27,891 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 14:59:27,978 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 14:59:28,006 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 14:59:28,031 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 14:59:28,112 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 14:59:46,554 - Database Import - INFO - Sever Connected !
2022-02-12 14:59:46,588 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 14:59:46,599 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 14:59:46,684 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 14:59:46,713 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 14:59:46,743 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 14:59:46,838 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:01:15,746 - Database Import - INFO - Sever Connected !
2022-02-12 15:01:15,790 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:01:15,804 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:01:15,913 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:01:15,944 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:01:15,972 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:01:16,051 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:02:37,639 - Database Import - INFO - Sever Connected !
2022-02-12 15:02:37,696 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:02:37,708 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:02:37,796 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:02:37,825 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:02:37,856 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:02:37,935 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:09:29,212 - Database Import - INFO - Sever Connected !
2022-02-12 15:09:29,264 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:09:29,275 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:09:29,364 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:09:29,392 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:09:29,421 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:09:29,499 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:09:36,744 - Database Import - INFO - Sever Connected !
2022-02-12 15:09:36,787 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:09:36,803 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:09:36,902 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:09:36,930 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:09:36,953 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:09:37,040 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:13:25,862 - Database Import - INFO - Sever Connected !
2022-02-12 15:13:25,901 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:13:25,915 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:13:26,044 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:13:26,096 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:13:26,133 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:13:26,224 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:14:14,320 - Database Import - INFO - Sever Connected !
2022-02-12 15:14:14,374 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:14:14,385 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:14:14,473 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:14:14,501 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:14:14,531 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:14:14,606 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:31:37,978 - Database Import - INFO - Sever Connected !
2022-02-12 15:31:38,032 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:31:38,045 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:31:38,132 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:31:38,159 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:31:38,182 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:31:38,263 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:31:44,837 - Database Import - INFO - Sever Connected !
2022-02-12 15:31:44,894 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:31:44,906 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:31:44,990 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:31:45,019 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:31:45,041 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:31:45,121 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:36:50,208 - Database Import - INFO - Sever Connected !
2022-02-12 15:36:50,243 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:36:50,258 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:36:50,344 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:36:50,372 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:36:50,400 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:36:50,479 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:37:55,000 - Database Import - INFO - Sever Connected !
2022-02-12 15:37:55,040 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:37:55,052 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:37:55,141 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:37:55,168 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:37:55,193 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:37:55,288 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:38:06,946 - Database Import - INFO - Sever Connected !
2022-02-12 15:38:06,999 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:38:07,012 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:38:07,094 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:38:07,121 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:38:07,144 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:38:07,241 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:38:37,810 - Database Import - INFO - Sever Connected !
2022-02-12 15:38:37,851 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:38:37,869 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:38:37,964 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:38:37,997 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:38:38,023 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:38:38,102 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:38:46,951 - Database Import - INFO - Sever Connected !
2022-02-12 15:38:46,987 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:38:47,002 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:38:47,094 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:38:47,121 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:38:47,157 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:38:47,261 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:39:00,773 - Database Import - INFO - Sever Connected !
2022-02-12 15:39:00,809 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:39:00,823 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:39:00,907 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:39:00,935 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:39:00,959 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:39:01,050 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:40:07,217 - Database Import - INFO - Sever Connected !
2022-02-12 15:40:07,285 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:40:07,297 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:40:07,385 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:40:07,413 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:40:07,444 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:40:07,526 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:41:38,818 - Database Import - INFO - Sever Connected !
2022-02-12 15:41:38,865 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:41:38,879 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:41:38,963 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:41:38,989 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:41:39,024 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:41:39,123 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:42:58,003 - Database Import - INFO - Sever Connected !
2022-02-12 15:42:58,055 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:42:58,069 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:42:58,153 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:42:58,186 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:42:58,213 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:42:58,289 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:44:55,072 - Database Import - INFO - Sever Connected !
2022-02-12 15:44:55,133 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:44:55,144 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:44:55,233 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:44:55,262 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:44:55,285 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:44:55,369 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:45:12,057 - Database Import - INFO - Sever Connected !
2022-02-12 15:45:12,120 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:45:12,134 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:45:12,217 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:45:12,243 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:45:12,267 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:45:12,345 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:45:18,868 - Database Import - INFO - Sever Connected !
2022-02-12 15:45:18,902 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:45:18,913 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:45:19,000 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:45:19,027 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:45:19,054 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:45:19,131 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:46:45,717 - Database Import - INFO - Sever Connected !
2022-02-12 15:46:45,774 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:46:45,789 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:46:45,902 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:46:45,941 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:46:45,983 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:46:46,064 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 15:47:29,554 - Database Import - INFO - Sever Connected !
2022-02-12 15:47:29,607 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 15:47:29,623 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 15:47:29,733 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 15:47:29,776 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 15:47:29,812 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 15:47:29,938 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:00:45,287 - Database Import - INFO - Sever Connected !
2022-02-12 16:00:45,358 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:00:45,374 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:00:45,478 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:00:45,515 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:00:45,556 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:00:45,656 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:01:13,706 - Database Import - INFO - Sever Connected !
2022-02-12 16:01:13,766 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:01:13,777 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:01:13,866 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:01:13,898 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:01:13,929 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:01:14,036 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:03:23,024 - Database Import - INFO - Sever Connected !
2022-02-12 16:03:23,081 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:03:23,094 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:03:23,202 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:03:23,237 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:03:23,269 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:03:23,347 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:44:10,097 - Database Import - INFO - Sever Connected !
2022-02-12 16:44:10,200 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:44:10,213 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:44:10,301 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:44:10,329 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:44:10,356 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:44:10,433 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:44:17,118 - Database Import - INFO - Sever Connected !
2022-02-12 16:44:17,158 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:44:17,169 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:44:17,257 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:44:17,282 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:44:17,312 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:44:17,401 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:46:24,960 - Database Import - INFO - Sever Connected !
2022-02-12 16:46:25,002 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:46:25,016 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:46:25,128 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:46:25,187 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:46:25,233 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:46:25,351 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:49:16,157 - Database Import - INFO - Sever Connected !
2022-02-12 16:49:16,192 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:49:16,203 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:49:16,292 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:49:16,321 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:49:16,352 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:49:16,439 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 16:49:23,153 - Database Import - INFO - Sever Connected !
2022-02-12 16:49:23,211 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 16:49:23,223 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 16:49:23,321 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 16:49:23,346 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 16:49:23,370 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 16:49:23,450 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 17:09:26,662 - Database Import - INFO - Sever Connected !
2022-02-12 17:09:26,700 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 17:09:26,711 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 17:09:26,800 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 17:09:26,829 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 17:09:26,855 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 17:09:26,946 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 17:09:33,700 - Database Import - INFO - Sever Connected !
2022-02-12 17:09:33,758 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 17:09:33,770 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 17:09:33,862 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 17:09:33,893 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 17:09:33,920 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 17:09:33,998 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:47:24,118 - Database Import - INFO - Sever Connected !
2022-02-12 19:47:24,201 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:47:24,222 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:47:24,356 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:47:24,405 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:47:24,444 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:47:24,598 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:48:48,871 - Database Import - INFO - Sever Connected !
2022-02-12 19:48:48,935 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:48:48,951 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:48:49,072 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:48:49,127 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:48:49,162 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:48:49,278 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:48:57,908 - Database Import - INFO - Sever Connected !
2022-02-12 19:48:57,977 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:48:57,992 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:48:58,116 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:48:58,165 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:48:58,196 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:48:58,319 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:49:26,709 - Database Import - INFO - Sever Connected !
2022-02-12 19:49:26,754 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:49:26,767 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:49:26,895 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:49:26,945 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:49:26,985 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:49:27,116 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:49:40,108 - Database Import - INFO - Sever Connected !
2022-02-12 19:49:40,173 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:49:40,187 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:49:40,323 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:49:40,365 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:49:40,400 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:49:40,538 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:49:50,976 - Database Import - INFO - Sever Connected !
2022-02-12 19:49:51,033 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:49:51,056 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:49:51,175 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:49:51,216 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:49:51,259 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:49:51,373 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:50:09,982 - Database Import - INFO - Sever Connected !
2022-02-12 19:50:10,056 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:50:10,069 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:50:10,195 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:50:10,227 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:50:10,259 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:50:10,364 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:50:37,195 - Database Import - INFO - Sever Connected !
2022-02-12 19:50:37,269 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:50:37,288 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:50:37,418 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:50:37,466 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:50:37,493 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:50:37,606 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:51:05,568 - Database Import - INFO - Sever Connected !
2022-02-12 19:51:05,631 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:51:05,647 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:51:05,768 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:51:05,815 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:51:05,849 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:51:05,963 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:51:30,416 - Database Import - INFO - Sever Connected !
2022-02-12 19:51:30,487 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:51:30,505 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:51:30,676 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:51:30,730 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:51:30,765 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:51:30,924 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:51:56,321 - Database Import - INFO - Sever Connected !
2022-02-12 19:51:56,380 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:51:56,393 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:51:56,555 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:51:56,628 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:51:56,702 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:51:56,821 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:52:28,010 - Database Import - INFO - Sever Connected !
2022-02-12 19:52:28,052 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:52:28,081 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:52:28,217 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:52:28,253 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:52:28,304 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:52:28,434 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:52:58,208 - Database Import - INFO - Sever Connected !
2022-02-12 19:52:58,273 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:52:58,288 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:52:58,433 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:52:58,471 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:52:58,505 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:52:58,644 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:54:11,292 - Database Import - INFO - Sever Connected !
2022-02-12 19:54:11,354 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:54:11,369 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:54:11,483 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:54:11,523 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:54:11,582 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:54:11,943 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:55:20,797 - Database Import - INFO - Sever Connected !
2022-02-12 19:55:20,849 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:55:20,869 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:55:20,991 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:55:21,037 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:55:21,074 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:55:21,187 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:55:29,459 - Database Import - INFO - Sever Connected !
2022-02-12 19:55:29,503 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:55:29,532 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:55:29,667 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:55:29,698 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:55:29,753 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:55:29,879 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:55:56,068 - Database Import - INFO - Sever Connected !
2022-02-12 19:55:56,147 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:55:56,168 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:55:56,334 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:55:56,376 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:55:56,417 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:55:56,644 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:56:59,563 - Database Import - INFO - Sever Connected !
2022-02-12 19:56:59,656 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:56:59,684 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:56:59,978 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:57:00,044 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:57:00,126 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:57:00,282 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:58:07,979 - Database Import - INFO - Sever Connected !
2022-02-12 19:58:08,030 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:58:08,047 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:58:08,180 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:58:08,211 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:58:08,252 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:58:08,364 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 19:59:35,105 - Database Import - INFO - Sever Connected !
2022-02-12 19:59:35,151 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 19:59:35,172 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 19:59:35,305 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 19:59:35,340 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 19:59:35,389 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 19:59:35,517 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:00:04,737 - Database Import - INFO - Sever Connected !
2022-02-12 20:00:04,835 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:00:04,873 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:01:02,150 - Database Import - INFO - Sever Connected !
2022-02-12 20:01:02,211 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:01:02,235 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:01:02,366 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:01:02,399 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:01:02,434 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:01:02,571 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:01:11,635 - Database Import - INFO - Sever Connected !
2022-02-12 20:01:11,699 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:01:11,720 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:01:11,845 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:01:11,901 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:01:11,931 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:01:12,050 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:02:12,606 - Database Import - INFO - Sever Connected !
2022-02-12 20:02:12,695 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:02:12,717 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:02:12,854 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:02:12,916 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:02:12,963 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:02:13,110 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:05:13,744 - Database Import - INFO - Sever Connected !
2022-02-12 20:05:13,792 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:05:13,811 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:05:13,918 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:05:13,950 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:05:13,983 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:05:14,125 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:10:17,507 - Database Import - INFO - Sever Connected !
2022-02-12 20:10:17,563 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:10:17,577 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:10:17,713 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:10:17,761 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:10:17,809 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:10:17,936 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:17:35,874 - Database Import - INFO - Sever Connected !
2022-02-12 20:17:35,991 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:17:36,096 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:17:36,236 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:17:36,307 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:17:36,338 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:17:36,564 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:22:18,805 - Database Import - INFO - Sever Connected !
2022-02-12 20:22:18,853 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:22:18,881 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:22:19,030 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:22:19,087 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:22:19,131 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:22:19,387 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:31:43,179 - Database Import - INFO - Sever Connected !
2022-02-12 20:31:43,264 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:31:43,277 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:31:43,458 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:31:43,503 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:31:43,548 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:31:43,657 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:32:08,258 - Database Import - INFO - Sever Connected !
2022-02-12 20:32:08,308 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:32:08,335 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:32:08,461 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:32:08,493 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:32:08,546 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:32:08,758 - Database Import - INFO - CPI Monthly.csv file created
2022-02-12 20:32:41,191 - Database Import - INFO - Sever Connected !
2022-02-12 20:32:41,278 - Database Import - INFO - Export Merchandise Monthly.csv file created
2022-02-12 20:32:41,313 - Database Import - INFO - Export Merchandise Yearly.csv file created
2022-02-12 20:32:41,473 - Database Import - INFO - Exchange Rate Monthly.csv file created
2022-02-12 20:32:41,533 - Database Import - INFO - CPI Yearly.csv file created
2022-02-12 20:32:41,562 - Database Import - INFO - Exchange Rate Yearly.csv file created
2022-02-12 20:32:41,702 - Database Import - INFO - CPI Monthly.csv file created
